delete from TMP_ARCHIVALFILESIZE;
delete from TMP_CORPUSOBJECT;
delete from TMP_INDEXMAP;
delete from TMP_PHOTOOBJECT;
delete from TMP_SPATIALREFERENCING;
delete from TMP_TEXTALIASES;
delete from  TMP_TEXTDIVISION;
delete from TMP_TEXTOBJECT;
delete from TMP_TIMEPERIODOBJECT;
delete from ERR_CORPUSOBJECT;
delete from ERR_INDEXMAP;
delete from ERR_PHOTOOBJECT;
delete from ERR_SPATIALREFERENCING;
delete from  ERR_TEXTOBJECT;
delete from ERR_TIMEPERIODOBJECT;


        