create or replace procedure textobjectinsert is
	-- Should be selected unique with textdisplayandsearchcode is null
       cursor CurTextObject is select * from tmp_textobject ;

MyErrorCode			number ;
MyErrorMessage			varchar2(200) ;

ctr integer ;

begin
      for i in CurTextObject loop
	begin 
          insert into textobject
		(ISFASSIGNEDTEXTNO
		,ALTTEXTTITLE
		,ANCIENTCITYORLOCATION
		,ANCIENTSTRUCTURE
		,DATEOFINSCRIPTIONNOTE
		,EXCAVATIONDESCRIPTION
		,EXCAVATIONNO
		,GEOGRAPHICALCOVERAGENOTE
		,INDEXMAPFILENAME
		,ISPARTOF
		,ISPARTOFCORPUS
		,ISPARTOFCORPUSCATEGORY
		,ISPARTOFCORPUSSUBCATEGORY
		,ISVERSIONOF
		,ISFFINDSITE
		,KEYWORDSORPHRASES
		,LANGUAGE
		,LOCATIONOFORIGINAL
		,MAINTEXTORPUBLCNNO
		,MAINTEXTORPUBLCNNOPREFIX
		,MAINTEXTORPUBLCNNOSUFFIX
		,MEDIUM
		,MODERNCITYORLOCATION
		,MODERNCOUNTRY
		,MUSEUMACCESSIONNO
		,NAMEDTIMEPERIOD
		,PHYSICALOBJECTDESCRIPTION
		,PHYSICALOBJECTNOTE
		,REGION
		,RELEVANTTIMELINE
		,RIGHTSPHYSICALOBJECT
		,SCRIPT
		,TEXTDESCRIPTION
		,TEXTDESCRIPTIVETITLE
		,TEXTORPUBLCNNONOTE
		,TEXTSEARCHANDDISPLAYCODE
                ,TEXTVIEW	
		,TEXTUNINSCRIBEDARTIFACT
		,TYPEOFITEMCATELOGED
		,TEXTALIASES
		,textdivision
		,LANGUAGENOTE   
		,SCRIPTNOTE     
       )
       values(i.ISFASSIGNEDTEXTNO
                ,alttexttitle_va(i.ALTTEXTTITLE1,i.ALTTEXTTITLE2,i.ALTTEXTTITLE3,i.ALTTEXTTITLE4,i.ALTTEXTTITLE5)
		,i.ANCIENTCITYORLOCATION
		,i.ANCIENTSTRUCTURE
		,i.DATEOFINSCRIPTIONNOTE
		,substr(trim(i.EXCAVATIONDESCRIPTION),1,520)
		,excavationno_va(i.EXCAVATIONNO,i.EXCAVATIONNO1,i.EXCAVATIONNO2,i.EXCAVATIONNO3,
                                 i.EXCAVATIONNO4,i.EXCAVATIONNO5,i.EXCAVATIONNO6,i.EXCAVATIONNO7,
                                 i.EXCAVATIONNO8,i.EXCAVATIONNO9)
		,i.GEOGRAPHICALCOVERAGENOTE
		,INDEXMAPFILENAME_VA(I.INDEXMAPFILENAME)
		,i.ISPARTOF
 		,Ispartofcorpus_va(i.ISPARTOFCORPUS,i.ISPARTOFCORPUS1,i.ISPARTOFCORPUS2)
		,ISPARTOFCORPUSCATEGORY_VA(i.ISPARTOFCORPUSCATEGORY,i.ISPARTOFCORPUS1CATEGORY,i.ISPARTOFCORPUS2CATEGORY)
		,ISPARTOFCORPUSSUBCATEGORY_VA(i.ISPARTOFCORPUSSUBCATEGORY,i.ISPARTOFCORPUS1SUBCATEGORY,i.ISPARTOFCORPUS2SUBCATEGORY)
		,i.ISVERSIONOF
		,i.ISFFINDSITE
                ,keywordsorphrases_va(i.KEYWORDSORPHRASES1,i.KEYWORDSORPHRASES2,
                    i.KEYWORDSORPHRASES3,i.KEYWORDSORPHRASES4,i.KEYWORDSORPHRASES5,
                    i.KEYWORDSORPHRASES6,i.KEYWORDSORPHRASES7,i.KEYWORDSORPHRASES8,
                    i.KEYWORDSORPHRASES9,i.KEYWORDSORPHRASES10,i.KEYWORDSORPHRASES11,
                    i.KEYWORDSORPHRASES12,i.KEYWORDSORPHRASES13,i.KEYWORDSORPHRASES14,
                    i.KEYWORDSORPHRASES15,i.KEYWORDSORPHRASES16,i.KEYWORDSORPHRASES17,
                    i.KEYWORDSORPHRASES18,i.KEYWORDSORPHRASES19,i.KEYWORDSORPHRASES20,
                   i.KEYWORDSORPHRASES21,i.KEYWORDSORPHRASES22,i.KEYWORDSORPHRASES23,
                   i.KEYWORDSORPHRASES24,i.KEYWORDSORPHRASES25)
		,language_va(i.LANGUAGE,i.LANGUAGE1,i.LANGUAGE2,i.LANGUAGE3)
		,locationoforiginal_va(i.LOCATIONOFORIGINAL,i.LOCATIONOFORIGINAL1,i.LOCATIONOFORIGINAL2,
                                      i.LOCATIONOFORIGINAL3,i.LOCATIONOFORIGINAL4,i.LOCATIONOFORIGINAL5)
		,i.MAINTEXTORPUBLCNNO
		,i.MAINTEXTORPUBLCNNOPREFIX
		,i.MAINTEXTORPUBLCNNOSUFFIX
		,i.MEDIUM
		,i.MODERNCITYORLOCATION
		,i.MODERNCOUNTRY
                ,museumaccessionno_va(i.MUSEUMACCESSIONNO1,i.MUSEUMACCESSIONNO2,
                    i.MUSEUMACCESSIONNO3,i.MUSEUMACCESSIONNO4,i.MUSEUMACCESSIONNO5,
                    i.MUSEUMACCESSIONNO6,i.MUSEUMACCESSIONNO7,i.MUSEUMACCESSIONNO8,
                    i.MUSEUMACCESSIONNO9,i.MUSEUMACCESSIONNO10,i.MUSEUMACCESSIONNO11,
                    i.MUSEUMACCESSIONNO12,i.MUSEUMACCESSIONNO13,i.MUSEUMACCESSIONNO14,
                   i.MUSEUMACCESSIONNO15,i.MUSEUMACCESSIONNO16,i.MUSEUMACCESSIONNO17,
                   i.MUSEUMACCESSIONNO18,i.MUSEUMACCESSIONNO19,i.MUSEUMACCESSIONNO20,
                   i.MUSEUMACCESSIONNO21,i.MUSEUMACCESSIONNO22,i.MUSEUMACCESSIONNO23,
                   i.MUSEUMACCESSIONNO24,i.MUSEUMACCESSIONNO25)
		,NAMEDTIMEPERIOD_VA(i.NAMEDTIMEPERIOD,i.NAMEDTIMEPERIOD1)
		,i.PHYSICALOBJECTDESCRIPTION
                ,physicalobjectnote_va(i.PHYSICALOBJECTNOTE,i.PHYSICALOBJECTNOTE1)
		,i.REGION
		,i.RELEVANTTIMELINE
                ,rightsphysicalobject_va(i.RIGHTSPHYSICALOBJECT,i.RIGHTSPHYSICALOBJECT1,i.RIGHTSPHYSICALOBJECT2,
                                         i.RIGHTSPHYSICALOBJECT3,i.RIGHTSPHYSICALOBJECT4)
		,script_nt(script_ty(i.SCRIPT,i.SCRIPTSUBLEVEL)
			   ,script_ty(i.SCRIPT1,i.SCRIPT1SUBLEVEL)
			   ,script_ty(i.SCRIPT2,i.SCRIPT2SUBLEVEL)
			   ,script_ty(i.SCRIPT3,i.SCRIPT3SUBLEVEL))
		,i.TEXTDESCRIPTION
		,i.TEXTDESCRIPTIVETITLE
		,textorpublcnnonote_va(substr(trim(i.TEXTORPUBLCNNONOTE),1,75))
		,i.TEXTSEARCHANDDISPLAYCODE
		,TEXTVIEW_VA(I.TEXTVIEW,I.TEXTVIEW1,I.TEXTVIEW2,I.TEXTVIEW3,I.TEXTVIEW4,
                             I.TEXTVIEW5,I.TEXTVIEW6,I.TEXTVIEW7,I.TEXTVIEW8,I.TEXTVIEW9)
                ,i.TEXTUNINSCRIBEDARTIFACT	
		,i.TYPEOFITEMCATELOGED
                ,cast(multiset(select a.ALTTEXTORPUBLCNNO,a.ALTTEXTORPUBLCNNOPREFIX,
                              a.ALTTEXTORPUBLCNNOSUFFIX,a.TEXTDESCRPTIVETITLE
                              from tmp_textaliases a
                             where a.isfassignedtextno=i.isfassignedtextno)
                             as textaliases_nt)
		,cast(multiset(select b.INDEXMAPFILENAME 
			,b.SPATIALSEARCHCODE
			,b.TEXTDESCRIPTIVETITLE
			,b.TEXTDIVISION
			,b.TEXTDIVISIONSEQNO
			,b.TEXTDIVISIONDESCRIPTION
			,b.TEXTDIVISIONMUSEUMNO
			,b.TEXTVIEW
			,cast(multiset(select 	a.TEXTDIVISIONSUBDIVISIONSEQNO, 
						a.TXTDIVISIONSUBDIVISION
					from 	tmp_textdivision a 
					where 	a.isfassignedtextno = b.isfassignedtextno 
						and a.textdivision = b.textdivision 
						and a.textdivisionSubdivisionseqno is not null) as TEXTDIVISIONSUBDIVISION_nt)
				from tmp_textdivision b
				where b.isfassignedtextno = i.isfassignedtextno
				and b.textdivisionseqno is not null) as textdivision_nt)
			,i.LANGUAGENOTE
			,i.SCRIPTNOTE);

		commit;
		exception
			When others then
				MyErrorCode := SQLCODE ;
				MyErrorMessage := SQLERRM ;
				insert into err_TextObject(ISFASSIGNEDTEXTNO
							   ,ERRORLOGTIME           
							   ,ERRORCODE              
							   ,REASON                 
							   ,ERRORMESSAGE)
					values(  i.ISFAssignedtextno
						,sysdate()
						,MyErrorCode
						,'Insert Failed'
						,MyErrorMessage) ;

				null ;

		end ;
      		end loop;

 end textobjectinsert ;
/
