create table tmp_TextDivision
(MainTextOrPublcnNo		CHAR(20)
 ,TextDescriptiveTitle		CHAR(130)
 ,ISFAssignedTextNo		CHAR(13)
 ,SpatialSearchCode		CHAR(3)
 ,TextDivision			CHAR(50)
 ,TextDivisionSeqNo		CHAR(4)
 ,TxtDivisionSubDivision	CHAR(50)
 ,TextDivisionSubDivisionSeqNo	CHAR(3)
 ,TextView			CHAR(40)
 ,TextDivisionDescription	CHAR(100)
 ,TextDivisionMuseumNo		CHAR(100)
 ,IndexMapFileName 		CHAR(20))
/

create table tmp_textaliases
(AltTextOrPublcnNo		CHAR(75)
 ,ISFAssignedTextNo		CHAR(13)
 ,MainTextOrPublcnNo		CHAR(20)
 ,TextDescrptiveTitle		CHAR(130)
 ,AltTextorPublcnNoPrefix	CHAR(20)
 ,AltTextOrPublcnNoSuffix	CHAR(50))	
/


create table tmp_corpusObject
(ISFAssignedCorpusIDNo		CHAR(13)
 ,CorpusName			CHAR(60)
 ,CorpusDesc			char(120)
 ,CorpusCategory		CHAR(60)
 ,COrpusCategorySeqNo		NUMBER(2)
 ,CorpusSubCategory		CHAR(60)
 ,CorpusSubCategorySeqNo	NUMBER(2))
/


create table tmp_indexMap
(IndexMapFileName		CHAR(20)
 ,ISFAssignedTextNo		CHAR(13)
 ,MainTextOrPublcnNo		CHAR(20)
 ,TextDivision			CHAR(50)
 ,TextSubDivision		Char(20)
 ,TextView 			CHAR(40))	
/


create table tmp_spatialReferencing
(referenceFile			CHAR(20)
 ,DetailedFile			CHAR(20)	
 ,DetailedLeft			CHAR(4)
 ,DetailedBottom		CHAR(4)
 ,DetailedWidth			CHAR(4)
 ,DetailedHeight 		CHAR(4))
/


create table tmp_textobject
(ISFAssignedTextNo		CHAR(13)
 ,MainTextOrPublcnNo		CHAR(25)
 ,MainTextOrPublcnNoPrefix	CHAR(25)
 ,MainTextOrPublcnNoSuffix	CHAR(25)
 ,AltTextOrPublcnNo		CHAR(75)
 ,TextSearchAndDisplayCode	CHAR(1)
 ,TextDivision			CHAR(50)	
 ,TextDivisionDescription	CHAR(100)
 ,TextDivisionMuseumNo		CHAR(100)
 ,TextDivisionSubDivision	CHAR(50)
 ,TextOrPublcnNoNote		CHAR(125)
 ,PhysicalObjectDescription	CHAR(250)
 ,PhysicalObjectNote		CHAR(520)
 ,PhysicalObjectNote1		CHAR(520)
 ,MuseumAccessionNo1		CHAR(30)
 ,MuseumAccessionNo2		CHAR(30)
 ,MuseumAccessionNo3		CHAR(30)
 ,MuseumAccessionNo4		CHAR(30)
 ,MuseumAccessionNo5		CHAR(30)
 ,MuseumAccessionNo6		CHAR(30)
 ,MuseumAccessionNo7		CHAR(30)
 ,MuseumAccessionNo8		CHAR(30)
 ,MuseumAccessionNo9		CHAR(30)
 ,MuseumAccessionNo10		CHAR(30)
 ,MuseumAccessionNo11		CHAR(30)
 ,MuseumAccessionNo12		CHAR(30)
 ,MuseumAccessionNo13		CHAR(30)
 ,MuseumAccessionNo14		CHAR(30)
 ,MuseumAccessionNo15		CHAR(30)
 ,MuseumAccessionNo16		CHAR(30)
 ,MuseumAccessionNo17		CHAR(30)
 ,MuseumAccessionNo18		CHAR(30)
 ,MuseumAccessionNo19		CHAR(30)
 ,MuseumAccessionNo20		CHAR(30)
 ,MuseumAccessionNo21		CHAR(30)
 ,MuseumAccessionNo22		CHAR(30)
 ,MuseumAccessionNo23		CHAR(30)
 ,MuseumAccessionNo24		CHAR(30)
 ,MuseumAccessionNo25		CHAR(30)
 ,TextView			CHAR(40)
 ,TextView1			CHAR(40)
 ,TextView2			CHAR(40)
 ,TextView3			CHAR(40)
 ,TextView4			CHAR(40)
 ,TextView5			CHAR(40)
 ,TextView6			CHAR(40)
 ,TextView7			CHAR(40)
 ,TextView8			CHAR(40)
 ,TextView9			CHAR(40)
 ,IsPartOfCorpus		CHAR(60)
 ,IsPartOfCorpusCategory	CHAR(60)	
 ,IsPartOfCorpusSubCategory	CHAR(60)
 ,IsPartOfCorpus1		CHAR(60)
 ,IsPartOfCorpus1Category	CHAR(60)	
 ,IsPartOfCorpus1SubCategory	CHAR(60)
 ,IsPartOfCorpus2		CHAR(60)
 ,IsPartOfCorpus2Category	CHAR(60)	
 ,IsPartOfCorpus2SubCategory	CHAR(60)
 ,IsVersionOf			CHAR(60)
 ,IsPartOf			CHAR(60)
 ,TextUninscribedArtifact	CHAR(40)	
 ,TypeOfItemCateloged		CHAR(20)
 ,Medium			CHAR(20)
 ,TextDescriptiveTitle		CHAR(130)
 ,AltTextTitle1			CHAR(200)
 ,AltTextTitle2			CHAR(200)
 ,AltTextTitle3			CHAR(200)
 ,AltTextTitle4			CHAR(200)
 ,AltTextTitle5			CHAR(200) 
 ,TextDescription		CHAR(250)
 ,ExcavationDescription		CHAR(520)
 ,ExcavationNo			CHAR(30)
 ,ExcavationNo1			CHAR(30)
 ,ExcavationNo2			CHAR(30)
 ,ExcavationNo3			CHAR(30)
 ,ExcavationNo4			CHAR(30)
 ,ExcavationNo5			CHAR(30)
 ,ExcavationNo6			CHAR(30)
 ,ExcavationNo7			CHAR(30)
 ,ExcavationNo8			CHAR(30)
 ,ExcavationNo9			CHAR(30)
 ,GeographicalCoverageNote	CHAR(60)
 ,SCRIPTNOTE                    CHAR(50)
 ,Script			CHAR(30)
 ,ScriptSubLevel		CHAR(20)
 ,Script1			CHAR(30)
 ,Script1SubLevel		CHAR(20)
 ,Script2			CHAR(30)
 ,Script2SubLevel		CHAR(20)
 ,Script3			CHAR(30)
 ,Script3SubLevel		CHAR(20)
 ,LANGUAGENOTE                  CHAR(50)
 ,Language			CHAR(50)
 ,Language1			CHAR(50)
 ,Language2			CHAR(50)
 ,Language3			CHAR(50)
 ,RelevantTimeLine		CHAR(20)
 ,NamedTimePeriod		CHAR(50)
 ,NamedTimePeriod1		CHAR(50)
 ,DateOfInscriptionNote		CHAR(60)
 ,AncientCityOrLocation		CHAR(40)
 ,AncientStructure		CHAR(40)
 ,ISFFIndsite			CHAR(40)
 ,ModernCityOrLocation		CHAR(40)
 ,ModernCountry			CHAR(30)
 ,Region			CHAR(40)
 ,LocationOfOriginal		CHAR(100)
 ,LocationOfOriginal1		CHAR(100)
 ,LocationOfOriginal2		CHAR(100)
 ,LocationOfOriginal3		CHAR(100)
 ,LocationOfOriginal4		CHAR(100)
 ,LocationOfOriginal5		CHAR(100)
 ,RightsPhysicalObject		CHAR(100)
 ,RightsPhysicalObject1		CHAR(100)
 ,RightsPhysicalObject2		CHAR(100)
 ,RightsPhysicalObject3		CHAR(100)
 ,RightsPhysicalObject4		CHAR(100) 
 ,keywordsOrPhrases1		CHAR(50)
 ,keywordsOrPhrases2		CHAR(50)		
 ,keywordsOrPhrases3		CHAR(50)
 ,keywordsOrPhrases4		CHAR(50)
 ,keywordsOrPhrases5		CHAR(50)
 ,keywordsOrPhrases6		CHAR(50)
 ,keywordsOrPhrases7		CHAR(50)
 ,keywordsOrPhrases8		CHAR(50)
 ,keywordsOrPhrases9		CHAR(50)
 ,keywordsOrPhrases10		CHAR(50)
 ,keywordsOrPhrases11		CHAR(50)
 ,keywordsOrPhrases12		CHAR(50)
 ,keywordsOrPhrases13		CHAR(50)
 ,keywordsOrPhrases14		CHAR(50)
 ,keywordsOrPhrases15		CHAR(50)
 ,keywordsOrPhrases16		CHAR(50)
 ,keywordsOrPhrases17		CHAR(50)
 ,keywordsOrPhrases18		CHAR(50)
 ,keywordsOrPhrases19		CHAR(50)
 ,keywordsOrPhrases20		CHAR(50)
 ,keywordsOrPhrases21		CHAR(50)
 ,keywordsOrPhrases22		CHAR(50)
 ,keywordsOrPhrases23		CHAR(50)
 ,keywordsOrPhrases24		CHAR(50)
 ,keywordsOrPhrases25		CHAR(50) 
 ,IndexMapFileName		CHAR(20))
/
create index IXtmptxtobj1 on tmp_textobject(ISFAssignedTextNo)
tablespace isfindx
/

create table tmp_photoobject
( ISFDigitalObjectIdentifier	char(13)
 ,PhotographIDentificationNo	char(20) 
 ,ThumbnailHeader		char(50)
 ,PhotoDescriptiveTitle		char(40)
 ,PhotographDescription		char(200)
 ,AncientTextRepresented	char(20)	
 ,ISFAssignedTextNo		char(13)
 ,TextDivision			char(50)	
 ,TextDivisionSubDivision	char(50)
 ,TextVIew			char(40)
 ,TextVIew1			char(40)
 ,TextVIew2			char(40)
 ,TextVIew3			char(40)
 ,TextVIew4			char(40)
 ,TextVIew5			char(40)
 ,TextVIew6			char(40)
 ,TextVIew7			char(40)
 ,TextVIew8			char(40)
 ,TextVIew9			char(40)
 ,TypeOfItemCateloged		char(20)
 ,PhotoTextOrPublcnNoNote	char(150)
 ,DateOfPhotograph		char(10)
 ,Photographer1			char(20)
 ,Photographer2			char(20)
 ,Photographer3			char(20)
 ,Photographer4			char(20)
 ,Photographer5			char(20)
 ,RightsPhysicalObject		char(100)
 ,RightsPhysicalObject1		char(100)
 ,RightsPhysicalObject2		char(100)
 ,RightsPhysicalObject3		char(100)
 ,RightsPhysicalObject4		char(100)
 ,IsPartOfWSRProject		char(40)	
 ,PhotoMuseumAccessionNo        char(50)     
 ,PhotoMuseumAccessionNo1        char(50)
 ,PhotoMuseumAccessionNo2        char(50)
 ,PhotoMuseumAccessionNo3        char(50)
 ,PhotoMuseumAccessionNo4        char(50)
 ,PhotoMuseumAccessionNo5        char(50)
 ,PhotoMuseumAccessionNo6        char(50)
 ,PhotoMuseumAccessionNo7        char(50)
 ,PhotoMuseumAccessionNo8        char(50)
 ,PhotoMuseumAccessionNo9        char(50)
 ,PhotoMuseumAccessionNo10        char(50)
 ,PhotoMuseumAccessionNo11        char(50)
 ,PhotoMuseumAccessionNo12        char(50)
 ,PhotoMuseumAccessionNo13        char(50)
 ,PhotoMuseumAccessionNo14        char(50)
 ,PhotoMuseumAccessionNo15        char(50) 
 ,PhotoMuseumAccessionNo16        char(50)
 ,PhotoMuseumAccessionNo17        char(50)
 ,PhotoMuseumAccessionNo18        char(50)
 ,PhotoMuseumAccessionNo19        char(50)
 ,PhotoMuseumAccessionNo20        char(50)
 ,PhotoMuseumAccessionNo21        char(50)
 ,PhotoMuseumAccessionNo22       char(50)
 ,PhotoMuseumAccessionNo23        char(50)
 ,PhotoMuseumAccessionNo24        char(50)
 ,PhotoMuseumAccessionNoNote     char(75)
 ,Colaborator1			char(40)
 ,Colaborator2			char(40)
 ,Colaborator3			char(40)
 ,Colaborator4			char(40)
 ,Colaborator5			char(40) 
 ,PhotoDimensions		char(25)
 ,MagnificationCode		char(1)
 ,FilmTypeCode			char(2)
 ,DateOfDigitalConversion	char(10)	
 ,DigitalObjectFormat		char(20)
 ,ArchivalFileSize		char(8)
 ,ArchivalFileResolution	char(9)
 ,CompressedFormatExtension	char(4)
 ,CompressionRatio		char(8)
 ,CompressionRoutine		char(8)
 ,DigitalObjectTypeNote		char(20)
 ,DigitizationEquipmentSpecs	char(30)
 ,RightsDigitalObject		char(60)
 ,RighsPhotograph		char(60)
 ,SCRIPTNOTE                    CHAR(50)
 ,Script			char(30)
 ,ScriptSubLevel		char(20)
 ,Script1			char(30)
 ,Script1SubLevel		char(20)
 ,Script2			char(30)
 ,Script2SubLevel		char(20)
 ,Script3			char(30)
 ,Script3SubLevel		char(20) 
 ,LANGUAGENOTE                  CHAR(50)
 ,Language			char(50)
 ,Language1			char(50) 
 ,Language2			char(50)
 ,Language3			char(50)
 ,ISFFindSite			char(40)
 ,RelevantTimeLine		char(20)
 ,NamedTimeperiod		char(50)
 ,NamedTimeperiod1		char(50)
 ,MEDIUM                        CHAR(20)
)	
/
create index IXtmpphobj1 on tmp_photoobject(ISFDIGITALOBJECTIDENTIFIER)
tablespace isfindx
/

create table tmp_TimePeriodObject
(NamedTimePeriod			CHAR(50)  
 ,TimeLineName				CHAR(20)
 ,TimePeriodBeginDateBCE_CE		CHAR(6)
 ,TimePeriodBeginDateYear		CHAR(6)
 ,TimePeriodEndDateBCE_CE		CHAR(6)
 ,TimePeriodEndDateYear			CHAR(6)
 ,TimePeriodExplanationOrDesc		CHAR(50)
)
/


create table err_photoobject
(isfdigitalobjectidentifier 	char(13)
 ,ErrorLogTime			date
 ,errorCode			number
 ,Reason			varchar2(20)
 ,ErrorMessage			varchar2(200))
/

create table err_textObject
(ISFAssignedtextno 		char(13)
 ,ErrorLogTime			date
 ,errorCode			number
 ,Reason			varchar2(20)
 ,ErrorMessage			varchar2(200))
/


create table err_CorpusObject
(isfassignedcorpusidno		char(13)
 ,ErrorLogTime			date
 ,errorCode			number
 ,Reason			varchar2(20)
 ,ErrorMessage			varchar2(200))
/

create table err_spatialreferencing
(referenceFile			CHAR(20)
 ,DetailedLeft			CHAR(4)
 ,DetailedBottom		CHAR(4)
 ,DetailedWidth			CHAR(4)
 ,DetailedHeight 		CHAR(4)
 ,ErrorLogTime			date
 ,errorCode			number
 ,Reason			varchar2(20)
 ,ErrorMessage			varchar2(200))
/


create table err_indexmap
(ISFAssignedTextNo		CHAR(13)
 ,TextDivision			CHAR(50)
 ,TextSubDivision		Char(20)
 ,TextView 			CHAR(40)	
 ,ErrorLogTime			date
 ,errorCode			number
 ,Reason			varchar2(20)
 ,ErrorMessage			varchar2(200))
/


create table err_TimeperiodObject
(NamedTimePeriod		CHAR(50)  
 ,TimeLineName			CHAR(20)
 ,ErrorLogTime			date
 ,errorCode			number
 ,Reason			varchar2(20)
 ,ErrorMessage			varchar2(200))
/










